name: ZAP Authenticated API Scan

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  zap-api-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        spec:
          - 'https://your.api.domain.com/service1/openapi.json'
          - 'https://your.api.domain.com/service2/openapi.json'
          - 'https://your.api.domain.com/service3/openapi.json'  # Add more as needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install JQ
        run: sudo apt-get install -y jq

      - name: Download and Preprocess OpenAPI Spec with JWT
        run: |
          echo "Fetching and modifying OpenAPI spec from ${{ matrix.spec }}"
          curl -s "${{ matrix.spec }}" | jq --arg token "${{ secrets.JWT_TOKEN }}" '
            .components.securitySchemes.BearerAuth = {
              type: "http",
              scheme: "bearer",
              bearerFormat: "JWT"
            } |
            .security = [{"BearerAuth": []}]
          ' > processed-spec.json

      - name: Run ZAP API Scan on ${{ matrix.spec }}
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          target: 'file://$(pwd)/processed-spec.json'
          format: openapi
          fail_action: false
          report_html: 'zap_report_${{ matrix.spec }}.html'
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report-${{ matrix.spec }}
          path: zap_report_${{ matrix.spec }}.html
